[package]
name = "json_test"
version = "0.1.0"
authors = ["Christian Oudard <christian.oudard@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = { version = "^1", features = ["preserve_order"] }
 

